databricks/containers

README.md, ubuntu/dbfsfuse-py3/README.md, ubuntu/minimal/README.md, ubuntu/ssh/Dockerfile, ubuntu/ssh/README.md, ubuntu/standard/Dockerfile, ubuntu/standard/README.md
This PR adds
- `Standard` image, which is intended to have more feature parity with the current Runtime images.
- `SSH` image, which is an example for how to set up SSH in container services.
- Adds misc. READMEs
=> Add standard and ssh example images

ubuntu/dbfsfuse/Dockerfile
Make sure the USER env variable is set. The files exposed by dbfs-fuse will be owned by this user.
Within the container, the USER is always root.
=> Set USER env variable in dbfsfuse docker file

README.md
The link redirects to the main page.
=> Fix the link to Dockerhub

ubuntu/gpu/pytorch/pytorch.yml, ubuntu/gpu/tensorflow/tensorflow.yml, ubuntu/python/env.yml
Traitlets 5.0 introduced a breaking change with made it incompatible with our python shell in DBR. Users should use traitlets<5.0 to be compatible with DBR versions <= 7.3.
=> Add explicit traitlets version for DBR <= 7.3 compatibility.

ubuntu/gpu/README.md
As titled. We'll follow up with providing CUDA 11 compatible files.
=> [ES-86800] Add warning about using CUDA 11 in 8.x

ubuntu/python-conda/Dockerfile, ubuntu/python-conda/README.md, ubuntu/python-conda/env.yml
Add a conda recipe that will be used as an alternative for the python standard recipe (once the standard gets switched to virtualenv). Upgrade the conda and package versions to match the defaults in the latest MLR release.
This recipe will work with all runtimes (both before and after 9.0). However, its primary purpose is for DBR 9.0+, where the standard python DCS recipe will be updated to use virtualenv. This recipe gives customers who require conda an alternative (at the cost of not supporting notebook-scoped libraries from 9.0 onwards)
Tested on https://e2-dogfood.staging.cloud.databricks.com/?o=6051921418418893#setting/clusters/0703-185216-fatal50
Full environment description (with package dependencies) below:
```
name: dcs-minimal
channels:
- defaults
dependencies:
- …
```
=> [ML-16055] Add a new conda recipe for customers using DCS with DBR 9.0+

ubuntu/R/Dockerfile
Updated the R Dockerfile to use the Bionic version of RStudio instead of the Xenial version of RStudio, which also includes R 4.1 instead of R 5 and is build for Ubuntu 18.04 (Bionic).
=> Updated RStudio Server to Bionic

ubuntu/python/Dockerfile
IPython 7.19.0 is required for notebooks to work with Python autocomplete in the base Docker image for:
* databricksruntime/standard:8.x
* databricksruntime/standard:9.x
* databricksruntime/python:8.x
* databricksruntime/python:9.x
=> increase version of IPython to 7.19.0 for Notebooks

README.md
We haven't kept the Dockerfiles updated for every runtime version and we haven't ensured that updates are backwards compatible. Let's add a warning here so users are aware.
=> Add compatibility warning to README

ubuntu/R/Dockerfile, ubuntu/R/README.md, ubuntu/dbfsfuse/Dockerfile, ubuntu/dbfsfuse/README.md, ubuntu/minimal/Dockerfile, ubuntu/minimal/README.md, ubuntu/python/Dockerfile, ubuntu/python/README.md, ubuntu/ssh/Dockerfile, ubuntu/ssh/README.md, ubuntu/standard/Dockerfile, ubuntu/standard/README.md
This patch changes the dockerfile to be built compatibly with DBR 10.4, specifically the the linux version is upgraded to 20.04
Smoke tests were performed to verify that the following cases are supported:
* a basic spark command can work in scala
* a basic spark command can work in python
* a basic sql query works
* notebook-scoped python libraries can be installed with pip
* dbfs fuse works
=> Add DCS images that are compatible with DBR 10.4

ubuntu/R/Dockerfile
Updates rbase to be compatible with ubuntu 20 (focal)
* removed the hardcoded ubuntu name when adding repo
* hardcode hwriterPlus dependency since it's removed in newer versions of R
* install latest version of RStudio
=> Update rbase for ubuntu 20

ubuntu/R/Dockerfile
Need to install `virtualenv` for all docker images to make them work with DBR 11+.  Check [PROD-28567] for more details.
Manually built a [docker image](https://hub.docker.com/layers/205077020/msharifdb/milads-test/latest/images/sha256-03e2ff0eb30440285afd696ae64c17eefc10527927d9ae30d15218d5b1dab0e9?context=repo) `msharifdb/milads-test:latest` and created a cluster with the docker image on [E2 dogfood](https://e2-dogfood.staging.cloud.databricks.com/?o=6051921418418893#setting/clusters/0426-234449-x0yfx8sy/configuration) and ran some R commands in a notebook.
=> [PROD-28567] Install virtualenv for R image

ubuntu/python/Dockerfile
This PR fixes Python autocomplete by pinning the version of jedi and ipython.
It is manually tested by running the following operations in the container:
```
./ipython
import numpy as np
np.<tab key>
```
=> Fix Python autocomplete

ubuntu/python/Dockerfile
This PR updates Dockerfile to match how utilities related to Python environments are installed in DBR to support Python library features use cases.
We also updated the existing installed python package version on the file to match the DBR 10.4: https://docs.databricks.com/release-notes/runtime/10.4.html#system-environment
=> Update dockerfiles to support %pip to 10.4 LTS

ubuntu/python/Dockerfile
This PR updates Dockerfile to match how utilities related to Python environments are installed in DBR to support Python library features use cases.
We also updated the existing installed python package version on the file to match the latest DBR version: https://docs.databricks.com/release-notes/runtime/11.1.html#system-environment
=> Update dockerfiles to support %pip to master

ubuntu/python/Dockerfile
This PR updates Dockerfile to match how utilities related to Python environments are installed in DBR to support Python library features use cases.
We also updated the existing installed python package version on the file to match the DBR 9.1: https://docs.databricks.com/release-notes/runtime/9.1.html#system-environment
=> Update dockerfiles to support %pip to 9.1 LTS

experimental/ubuntu/files-in-repos/Dockerfile, experimental/ubuntu/files-in-repos/README.md
For DBR 11 LTS and above, Files in Repos will work with the standard DCS image.
For DBR 10.4 LTS, we provide this custom DCS image to start the Files in Repos FUSE daemon.
=> Create DCS image to enable Files in Repos for DBR 10.4

experimental/ubuntu/files-in-repos/Dockerfile, experimental/ubuntu/files-in-repos/README.md
For DBR 11 LTS and above, Files in Repos will work with the standard DCS image.
For DBR 9.1 LTS, we provide this custom DCS image to start the Files in Repos FUSE daemon.
=> Create DCS image to enable Files in Repos for DBR 9.1

ubuntu/minimal/README.md
This change adds a note in the README for adding the `spark.databricks.driverNfs.enabled false` Spark config while using this image with Databricks Runtime 11.x or higher.  This provides a workaround if the cluster startup fails because of the unavailability of `virtualenv` in the image.
=> Update minimal container README for DBR 11.x

ubuntu/R/README.md
See similar change made for the `minimal` image for context https://github.com/databricks/containers/pull/113
This change adds a note in the README for adding the spark.databricks.driverNfs.enabled false Spark config while using this image with Databricks Runtime 11.x or higher. This provides a workaround if the cluster startup fails because of the unavailability of virtualenv in the image.
=> Update R image description to use required Spark conf

ubuntu/R/Dockerfile
Microsoft has retired MRAN (https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161).  Accordingly, remove the MRAN repo from the Dockerfile.
=> Remove MRAN from Dockerfile

ubuntu/minimal/Dockerfile
This PR adds a new `libraries` user for use when installing cluster libraries.
=> Add libraries user

ubuntu/minimal/Dockerfile
This PR installs the `acl` package in the minimal image to allow manipulating file ACLs.
=> Install acl package

ubuntu/gpu/cuda-11.8/pytorch/Dockerfile
The pytorch GPU container is quite large, and building off of it is causing timeouts on Databricks.  See #142 .  Purging the pip cache after torch install seems to save about 2 GB on the image size.  Looks like this is done [here](https://github.com/databricks/containers/blob/master/ubuntu/gpu/cuda-11.8/venv/Dockerfile#L57) in the venv image but not done after the torch installs.  This PR fixes that.
=> Purge the pip cache after installing torch

ubuntu/gpu/README.md, ubuntu/gpu/cuda-11.8/venv/Dockerfile, ubuntu/gpu/cuda-11.8/venv/requirements.txt
The cuda-11.8 image hasn't been updated for a while, and it has Python REPL issue on a cluster with DBR 15.x; meanwhile, DBR 14.3 works. The cluster driver logs showed that the python package `pyccolo` was missing.
Changes:
1. Move requirements for `cuda-11.8/venv` to a dedicated `requirements.txt`
2. Add `pyccolo` to the file
Tested that Python REPL now works:
=> Install pyccolo in gpu cuda-11.8

ubuntu/python/Dockerfile
python has been updated to be 3.11 however comment stayed at 3.10, bringing those in sync
=> [comment fix] Update comment to reflect updated python version

ubuntu/standard/Dockerfile
Fix the following error, possibly caused by Ubuntu upgrade:
```
The command '/bin/sh -c useradd --create-home --shell /bin/bash --groups sudo ubuntu' returned a non-zero code: 9
```
I ran `lslogins` on the pre-created user and it matches what we have in DBR 16.3, so I think it should have the same behavior.
=> Remove useradd command which fails because the user already exists
